# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.cache/wt [current_project]
set_property parent.project_path /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/patmos/t-crest/patmos/hardware/vivado/genesys2/genesys2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/ddr2_ctrl/ddr2_ctrl.dcp
set_property used_in_implementation false [get_files /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/ddr2_ctrl/ddr2_ctrl.dcp]
add_files -quiet /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/clk_manager/clk_manager.dcp
set_property used_in_implementation false [get_files /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/clk_manager/clk_manager.dcp]
read_verilog -library xil_defaultlib /home/patmos/t-crest/patmos/hardware/vivado/patmos/Patmos.v
read_vhdl -library xil_defaultlib {
  /home/patmos/t-crest/patmos/hardware/vhdl/mem/HWA_PACKAGE.vhd
  /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/patmos_nexys4ddr.vhdl
  /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/new/ocp_burst_to_ddr2_ctrl.vhd
  /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/new/nexys4ddr_io.vhd
  /home/patmos/t-crest/patmos/hardware/vhdl/mem/bram_tdp.vhd
  /home/patmos/t-crest/patmos/hardware/vhdl/mem/n_bank.vhd
  /home/patmos/github/bachelor_project_HLS/hls/misc/matmul_float/hls_matmul_float/matmul_2b/impl/vhdl/matmul_hw_urem_4neOg.vhd
  /home/patmos/github/bachelor_project_HLS/hls/misc/matmul_float/hls_matmul_float/matmul_2b/impl/vhdl/matmul_hw_mux_42_dEe.vhd
  /home/patmos/github/bachelor_project_HLS/hls/misc/matmul_float/hls_matmul_float/matmul_2b/impl/vhdl/matmul_hw.vhd
  /home/patmos/github/bachelor_project_HLS/hls/misc/matmul_float/hls_matmul_float/matmul_2b/impl/vhdl/matmul_hw_fmul_32cud.vhd
  /home/patmos/github/bachelor_project_HLS/hls/misc/matmul_float/hls_matmul_float/matmul_2b/impl/vhdl/matmul_hw_fadd_32bkb.vhd
}
read_ip -quiet /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/matmul_hw_ap_fmul_2_max_dsp_32/matmul_hw_ap_fmul_2_max_dsp_32.xci
set_property is_locked true [get_files /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/matmul_hw_ap_fmul_2_max_dsp_32/matmul_hw_ap_fmul_2_max_dsp_32.xci]

read_ip -quiet /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/matmul_hw_ap_fadd_3_full_dsp_32/matmul_hw_ap_fadd_3_full_dsp_32.xci
set_property is_locked true [get_files /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.srcs/sources_1/ip/matmul_hw_ap_fadd_3_full_dsp_32/matmul_hw_ap_fadd_3_full_dsp_32.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.xdc
set_property used_in_implementation false [get_files /home/patmos/t-crest/patmos/hardware/vivado/matmul_2b_float/matmul_2b_float.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top patmos_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef patmos_top.dcp

catch { report_utilization -file patmos_top_utilization_synth.rpt -pb patmos_top_utilization_synth.pb }
