# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/andreas/t-crest/patmos/hardware/vivado/matmul_float_3b_4x4/matmul_float.xdc

# IP: ip/matmul_hw_ap_fmul_2_max_dsp_32/matmul_hw_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_hw_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==matmul_hw_ap_fmul_2_max_dsp_32}]

# IP: ip/matmul_hw_ap_fadd_3_full_dsp_32/matmul_hw_ap_fadd_3_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_hw_ap_fadd_3_full_dsp_32 || ORIG_REF_NAME==matmul_hw_ap_fadd_3_full_dsp_32}]
