# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.xdc

# IP: ip/minver_hwa_ap_fmul_2_max_dsp_32/minver_hwa_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minver_hwa_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==minver_hwa_ap_fmul_2_max_dsp_32}]

# IP: ip/minver_hwa_ap_dcmp_0_no_dsp_64/minver_hwa_ap_dcmp_0_no_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minver_hwa_ap_dcmp_0_no_dsp_64 || ORIG_REF_NAME==minver_hwa_ap_dcmp_0_no_dsp_64}]

# IP: ip/minver_hwa_ap_fpext_0_no_dsp_32/minver_hwa_ap_fpext_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minver_hwa_ap_fpext_0_no_dsp_32 || ORIG_REF_NAME==minver_hwa_ap_fpext_0_no_dsp_32}]

# IP: ip/minver_hwa_ap_fdiv_14_no_dsp_32/minver_hwa_ap_fdiv_14_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minver_hwa_ap_fdiv_14_no_dsp_32 || ORIG_REF_NAME==minver_hwa_ap_fdiv_14_no_dsp_32}]

# IP: ip/minver_hwa_ap_fsub_3_full_dsp_32/minver_hwa_ap_fsub_3_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minver_hwa_ap_fsub_3_full_dsp_32 || ORIG_REF_NAME==minver_hwa_ap_fsub_3_full_dsp_32}]

# IP: ip/minver_hwa_ap_fcmp_0_no_dsp_32/minver_hwa_ap_fcmp_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minver_hwa_ap_fcmp_0_no_dsp_32 || ORIG_REF_NAME==minver_hwa_ap_fcmp_0_no_dsp_32}]
