# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager.xci
# IP: The module: 'clk_manager' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_manager'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager.xci
# IP: The module: 'clk_manager' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/matmul_1b_int/matmul_1b_int.srcs/sources_1/ip/clk_manager/clk_manager_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
