create_clock -period 10.000 [get_ports clk_in]
create_generated_clock -source [get_ports clk_in] -edges {1 2 3} -edge_shift {0.000 -2.500 -5.000} [get_ports -no_traverse clk_out_1]
create_generated_clock -source [get_ports clk_in] -edges {1 2 3} -edge_shift {0.000 45.000 90.000} [get_ports -no_traverse clk_out_2]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet clk_in]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet clk_in]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet clk_in]]
