# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-78001-ubuntu/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv /home/patmos/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog {
      ./.Xil/Vivado-78001-ubuntu/realtime/ddr2_ctrl_stub.v
      ./.Xil/Vivado-78001-ubuntu/realtime/clk_manager_stub.v
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/Patmos_HwACtrlExt.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/MEM_PACKAGE.vhd
      /home/patmos/t-crest/patmos/hardware/vhdl/mem/HWA_PACKAGE.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/patmos_nexys4ddr.vhdl
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/new/ocp_burst_to_ddr2_ctrl.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/new/nexys4ddr_io.vhd
      /home/patmos/t-crest/patmos/hardware/vhdl/mem/bram_tdp.vhd
      /home/patmos/t-crest/patmos/hardware/vhdl/mem/n_bank.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa_fsub_3bkb.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa_fmul_3cud.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa_work.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa_fdiv_3dEe.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa_dcmp_6g8j.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa_fpext_eOg.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa.vhd
      /home/patmos/github/bachelor_project_HLS/hls/tacle-bench/kernel/minver_float/hls_minver_float/minver_1b_32x32/impl/vhdl/minver_hwa_fcmp_3fYi.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/synth/minver_hwa_ap_fmul_2_max_dsp_32.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_dcmp_0_no_dsp_64/synth/minver_hwa_ap_dcmp_0_no_dsp_64.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fpext_0_no_dsp_32/synth/minver_hwa_ap_fpext_0_no_dsp_32.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fdiv_14_no_dsp_32/synth/minver_hwa_ap_fdiv_14_no_dsp_32.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fsub_3_full_dsp_32/synth/minver_hwa_ap_fsub_3_full_dsp_32.vhd
      /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fcmp_0_no_dsp_32/synth/minver_hwa_ap_fcmp_0_no_dsp_32.vhd
    }
      rt::read_vhdl -lib xbip_utils_v3_0_7 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_3 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_3 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_3 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_3 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_3 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_12 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_1_3 /home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.srcs/sources_1/ip/minver_hwa_ap_fmul_2_max_dsp_32/hdl/floating_point_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib xpm /home/patmos/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-78001-ubuntu/realtime/patmos_top_synth.xdc
    rt::sdcChecksum
    set rt::top patmos_top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/patmos/t-crest/patmos/hardware/vivado/minver_float_1b_32x32_buffer/minver_float.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-78001-ubuntu/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
