set_property SRC_FILE_INFO {cfile:/home/andreas/t-crest/patmos/hardware/vivado/nexys4ddr/nexys4ddr.srcs/sources_1/ip/ddr2_ctrl/ddr2_ctrl/user_design/constraints/ddr2_ctrl_ooc.xdc rfile:../../nexys4ddr.srcs/sources_1/ip/ddr2_ctrl/ddr2_ctrl/user_design/constraints/ddr2_ctrl_ooc.xdc id:1 order:EARLY rxprname:$PSRCDIR/sources_1/ip/ddr2_ctrl/ddr2_ctrl/user_design/constraints/ddr2_ctrl_ooc.xdc} [current_design]
set_property SRC_FILE_INFO {cfile:/home/andreas/t-crest/patmos/hardware/vivado/nexys4ddr/nexys4ddr.srcs/sources_1/ip/ddr2_ctrl/ddr2_ctrl/user_design/constraints/ddr2_ctrl.xdc rfile:../../nexys4ddr.srcs/sources_1/ip/ddr2_ctrl/ddr2_ctrl/user_design/constraints/ddr2_ctrl.xdc id:2 order:EARLY rxprname:$PSRCDIR/sources_1/ip/ddr2_ctrl/ddr2_ctrl/user_design/constraints/ddr2_ctrl.xdc} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
###################################################################################################
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## This constraints file contains default clock frequencies to be used during creation of a
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## to match the target frequencies.
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
###################################################################################################
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]

set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]

set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##################################################################################################
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##  Xilinx, Inc. 2010            www.xilinx.com
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##  Mon Feb 27 10:54:09 2017
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##  Generated by MIG Version 4.0
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##################################################################################################
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##  File name :       ddr2_ctrl.xdc
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##  Details :     Constraints file
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##                    FPGA Family:       ARTIX7
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##                    FPGA Part:         XC7A100T-CSG324
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##                    Speedgrade:        -1
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##                    Design Entry:      VERILOG
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##                    Frequency:         0 MHz
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##                    Time Period:       5000 ps
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##################################################################################################
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]

set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##################################################################################################
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## Controller 0
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## Memory Device: DDR2_SDRAM->Components->MT47H64M16HR-25E
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## Data Width: 16
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## Time Period: 5000
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
## Data Mask: 1
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
##################################################################################################
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]

set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 5.000 [get_ports sys_clk_i]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]

set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]

set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
##################################################################################################
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
##
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
##  Xilinx, Inc. 2010            www.xilinx.com
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
##  Mon Feb 27 10:54:09 2017
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
##  Generated by MIG Version 4.0
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
##
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
##################################################################################################
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
##  File name :       ddr2_ctrl.xdc
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
##  Details :     Constraints file
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
##                    FPGA Family:       ARTIX7
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
##                    FPGA Part:         XC7A100T-CSG324
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
##                    Speedgrade:        -1
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
##                    Design Entry:      VERILOG
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
##                    Frequency:         0 MHz
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
##                    Time Period:       5000 ps
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
##################################################################################################
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
##################################################################################################
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
## Controller 0
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
## Memory Device: DDR2_SDRAM->Components->MT47H64M16HR-25E
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
## Data Width: 16
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
## Time Period: 5000
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
## Data Mask: 1
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
##################################################################################################
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
#create_clock -period 5 [get_ports sys_clk_i]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
############## NET - IOSTANDARD ##################
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L23P_T3_34
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[0]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[0]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[0]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {ddr2_dq[0]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[0]} {set_property PACKAGE_PIN R7 [get_ports {ddr2_dq[0]}]} {MOD}
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L20N_T3_34
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[1]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[1]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[1]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {ddr2_dq[1]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[1]} {set_property PACKAGE_PIN V6 [get_ports {ddr2_dq[1]}]} {MOD}
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L24P_T3_34
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[2]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[2]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[2]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {ddr2_dq[2]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[2]} {set_property PACKAGE_PIN R8 [get_ports {ddr2_dq[2]}]} {MOD}
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L22P_T3_34
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[3]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[3]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[3]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {ddr2_dq[3]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[3]} {set_property PACKAGE_PIN U7 [get_ports {ddr2_dq[3]}]} {MOD}
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L20P_T3_34
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[4]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[4]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[4]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {ddr2_dq[4]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[4]} {set_property PACKAGE_PIN V7 [get_ports {ddr2_dq[4]}]} {MOD}
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L19P_T3_34
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[5]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[5]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[5]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {ddr2_dq[5]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[5]} {set_property PACKAGE_PIN R6 [get_ports {ddr2_dq[5]}]} {MOD}
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L22N_T3_34
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[6]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[6]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[6]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {ddr2_dq[6]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[6]} {set_property PACKAGE_PIN U6 [get_ports {ddr2_dq[6]}]} {MOD}
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L19N_T3_VREF_34
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[7]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[7]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[7]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {ddr2_dq[7]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[7]} {set_property PACKAGE_PIN R5 [get_ports {ddr2_dq[7]}]} {MOD}
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L12P_T1_MRCC_34
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[8]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[8]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[8]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {ddr2_dq[8]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[8]} {set_property PACKAGE_PIN T5 [get_ports {ddr2_dq[8]}]} {MOD}
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L8N_T1_34
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[9]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[9]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[9]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {ddr2_dq[9]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[9]} {set_property PACKAGE_PIN U3 [get_ports {ddr2_dq[9]}]} {MOD}
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L10P_T1_34
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[10]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[10]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[10]}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {ddr2_dq[10]}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[10]} {set_property PACKAGE_PIN V5 [get_ports {ddr2_dq[10]}]} {MOD}
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L8P_T1_34
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[11]}]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[11]}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[11]}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {ddr2_dq[11]}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[11]} {set_property PACKAGE_PIN U4 [get_ports {ddr2_dq[11]}]} {MOD}
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L10N_T1_34
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[12]}]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[12]}]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[12]}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {ddr2_dq[12]}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[12]} {set_property PACKAGE_PIN V4 [get_ports {ddr2_dq[12]}]} {MOD}
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L12N_T1_MRCC_34
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[13]}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[13]}]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[13]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddr2_dq[13]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[13]} {set_property PACKAGE_PIN T4 [get_ports {ddr2_dq[13]}]} {MOD}
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L7N_T1_34
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[14]}]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[14]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[14]}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {ddr2_dq[14]}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[14]} {set_property PACKAGE_PIN V1 [get_ports {ddr2_dq[14]}]} {MOD}
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L11N_T1_SRCC_34
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dq[15]}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dq[15]}]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[15]}]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddr2_dq[15]}]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
# tool_modified_constraint_info {PC_IO_PIN:TERMINAL:ddr2_dq[15]} {set_property PACKAGE_PIN T3 [get_ports {ddr2_dq[15]}]} {MOD}
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L18N_T2_34
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[12]}]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[12]}]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {ddr2_addr[12]}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L5P_T0_34
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[11]}]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[11]}]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr2_addr[11]}]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L15N_T2_DQS_34
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[10]}]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[10]}]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddr2_addr[10]}]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L13P_T2_MRCC_34
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[9]}]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[9]}]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {ddr2_addr[9]}]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L5N_T0_34
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[8]}]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[8]}]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ddr2_addr[8]}]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L3N_T0_DQS_34
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[7]}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[7]}]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {ddr2_addr[7]}]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L4N_T0_34
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[6]}]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[6]}]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {ddr2_addr[6]}]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L13N_T2_MRCC_34
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[5]}]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[5]}]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {ddr2_addr[5]}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L2N_T0_34
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[4]}]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[4]}]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ddr2_addr[4]}]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L17N_T2_34
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[3]}]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[3]}]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {ddr2_addr[3]}]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L18P_T2_34
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[2]}]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[2]}]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {ddr2_addr[2]}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L14P_T2_SRCC_34
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[1]}]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[1]}]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ddr2_addr[1]}]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L16P_T2_34
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_addr[0]}]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_addr[0]}]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {ddr2_addr[0]}]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L17P_T2_34
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_ba[2]}]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_ba[2]}]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ddr2_ba[2]}]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L14N_T2_SRCC_34
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_ba[1]}]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_ba[1]}]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {ddr2_ba[1]}]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L15P_T2_DQS_34
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_ba[0]}]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_ba[0]}]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {ddr2_ba[0]}]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L16N_T2_34
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr2_ras_n]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddr2_ras_n]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports ddr2_ras_n]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L1P_T0_34
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr2_cas_n]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddr2_cas_n]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports ddr2_cas_n]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L3P_T0_DQS_34
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr2_we_n]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddr2_we_n]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports ddr2_we_n]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L1N_T0_34
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_cke[0]}]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_cke[0]}]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {ddr2_cke[0]}]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L4P_T0_34
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_odt[0]}]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_odt[0]}]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports {ddr2_odt[0]}]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_0_34
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_cs_n[0]}]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_cs_n[0]}]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {ddr2_cs_n[0]}]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L23N_T3_34
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dm[0]}]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dm[0]}]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {ddr2_dm[0]}]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L7P_T1_34
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dm[1]}]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dm[1]}]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {ddr2_dm[1]}]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L21P_T3_DQS_34
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L21N_T3_DQS_34
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {ddr2_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L9P_T1_DQS_34
set_property src_info {type:XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L9N_T1_DQS_34
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr2_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddr2_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L6P_T0_34
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_ck_p[0]}]
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_ck_p[0]}]
set_property src_info {type:XDC file:2 line:275 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
# PadFunction: IO_L6N_T0_VREF_34
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr2_ck_n[0]}]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_ck_n[0]}]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports {ddr2_ck_n[0]}]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {ddr2_ck_p[0]}]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property INTERNAL_VREF 0.9 [get_iobanks 34]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
## set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
## set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:310 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/plle2_i}]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -setup -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 6
set_property src_info {type:XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 5
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -setup -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 2
set_property src_info {type:XDC file:2 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 1
set_property src_info {type:XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20.000
set_property src_info {type:XDC file:2 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] 5.000
set_property src_info {type:XDC file:2 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst}]
set_property src_info {type:XDC file:2 line:331 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr2_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20.000
set_property src_info {type:XDC file:2 line:333 export:INPUT save:INPUT read:READ} [current_design]

set_property src_info {type:XDC file:2 line:334 export:INPUT save:INPUT read:READ} [current_design]

