# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/patmos/t-crest/patmos/hardware/vivado/filterbank_float_256/filterbank.xdc

# IP: ip/filterbank_core_hwa_ap_fadd_3_full_dsp_32/filterbank_core_hwa_ap_fadd_3_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filterbank_core_hwa_ap_fadd_3_full_dsp_32 || ORIG_REF_NAME==filterbank_core_hwa_ap_fadd_3_full_dsp_32}]

# IP: ip/filterbank_core_hwa_ap_fmul_2_max_dsp_32/filterbank_core_hwa_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filterbank_core_hwa_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==filterbank_core_hwa_ap_fmul_2_max_dsp_32}]
